### ISSUE TITLE
Update code to run on new OR-Tools

### ISSUE THREAD

**Issue by ntalluri** [gitter-lab/min-cost-flow#2]
Currently runs on OR-Tools version: 9.3.10497

At one point, need to update the code to run on the updated version of OR-Tools

**Comment by agitter** [comment]
The changes needed for our script would likely be similar to those applied to the OR-Tools [sample code](https://github.com/google/or-tools/commit/52e439d5eff0191034e6a070d49ae6ed795b68cc#diff-515cac17515192d3af447807688565dee7c56025ef77bd7729e3a88c41255be7).

**Comment by agitter** [comment]
Closed by #5
